# Run tests and update code coverage on push and pull requests.

name: test

on:
  - push
  - pull_request

jobs:
  test:
    name: test and coverage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      env:
        NODE_ENV: test
      run: npm test

    # - name: Prepare coverage report
    #   env:
    #     NODE_ENV: test
    #   run: npx nyc report --reporter=lcov

    - name: Prepare coverage report
      env:
        NODE_ENV: test
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
        COVERALLS_GIT_BRANCH: ${GITHUB_REF##*/}
      run: npx nyc report --reporter=text-lcov | npx coveralls

    # - name: Send coverage data to coveralls.io
    #   run: npx coveralls
    #   with:
    #     github-token: ${{ secrets.GITHUB_TOKEN }}
